[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
ctrlc = "3.4.4"
rand = "0.8.5"
neural-network = { path = "../neural-network" }
serialization  = { path = "../serialization" }
math = { path = "../math" }
